name: dotnet
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v2

      #无法将框架克隆到/home/runner/work/osu以外，用此办法暂时规避
      - name: 移动项目
        run: |
          mkdir mfosu
          mv ./* mfosu || true #忽略错误，通配符会匹配mfosu
          mv ./.* mfosu || true #忽略错误，bash会把"."" 和 ".."也归进mv目标里
          if [ ! "$(ls)" == "mfosu" ]; then false; fi #检查当前目录，应当只有mfosu

      - name: 下载框架
        uses: actions/checkout@v2
        with:
          repository: 'MATRIX-feather/osu-framework'
          ref: 'stable'
          path: 'osu-framework'

      - name: 安装sdk (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 解决依赖
        working-directory: ./mfosu
        run: dotnet restore osu.Desktop

      - name: 构建
        working-directory: ./mfosu
        run: dotnet build osu.Desktop -c Release